<?php
    echo $this->Html->script([
        //'app/shared/jquery-2.1.4.min.js',
        'app/shared/angularJS/angular.min.js',
        'app/shared/jsencrypt.js',
        //'app/shared/css_browser_selector.js',
        'app/shared/uiBootstrap/ui-bootstrap.min',
        'app/shared/angularJS/angular-animate.min',
        'app/shared/angularJS/angular-touch.min',
        'app/shared/angularJS/angular-cookies.min',
        'app/shared/uiRouter/angular-ui-router.min',
        'app/shared/stopEvent/stop-event',
        'app/shared/ngFileUpload/ng-file-upload-shim.min', 'app/shared/ngFileUpload/ng-file-upload.min',
        'app/shared/ngProgressBar/ng-progress-bar', 'app/shared/ngFileUploader/ng-file-uploader',
        'app/shared/dfaCustomControls/custom-controls', 'app/shared/loadingBar/loading-bar.js',
        'app/shared/ngMask/ng-mask.js', 'app/shared/angularLocalStorage/angular-local-storage.js',
        'app/shared/ngLayoutSplitter/ng-layout-splitter.js',
        'app/shared/uiGrid/ui-grid.min',
        'app/shared/pdfMake/pdfmake.min',
        'app/shared/pdfMake/vfs_fonts',
        'app/appConfig','app/app', 
        'app/components/home/home.module', 'app/components/home/home.controller', 'app/components/home/home.service',
        'app/components/planning/planning.module', 'app/components/planning/planning.controller', 'app/components/planning/planning.service',
        'app/components/translations/translations.module', 'app/components/translations/translations.controller', 'app/components/translations/translations.service',
        'app/components/userManagement/userManagement.module', 'app/components/userManagement/userManagement.controller', 'app/components/userManagement/userManagement.service',
        'app/components/core/core.filter','app/components/core/core.directive', 'app/components/core/core.controller', 'app/components/core/core.service', 'app/components/core/core.constant', 'app/components/core/core.config']);
